# Generated by Django 5.2.6 on 2025-09-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunteur',
            name='bloque',
            field=models.BooleanField(default=False),
        ),
    ]
